### ISSUE TITLE
可以支持angular 13版本吗

### ISSUE THREAD

**Issue by m310851010** [acrodata/watermark#1]
公司是老项目了，用的angular 13版本，可以支持一下吗？谢谢

**Comment by nzbin** [comment]
库里面包含一个 Watermark 类和一个封装好的指令，低版本的话可以直接 new Watermark 或者自己封装指令
```ts
new Watermark(options);
```
https://stackblitz.com/edit/angular-13-starter-project-etixiw?file=src%2Fapp%2Fapp.component.ts

**Comment by m310851010** [comment]
> 库里面包含一个 Watermark 类和一个封装好的指令，低版本的话可以直接 new Watermark 或者自己封装指令
> 
> ```ts
> new Watermark(options);
> ```
> 
> https://stackblitz.com/edit/angular-13-starter-project-etixiw?file=src%2Fapp%2Fapp.component.ts

3q
